import { mkdirSync, existsSync } from "node:fs";
import { join, extname, basename } from "node:path";
import { randomUUID } from "node:crypto";

export function documentsPath() {
  // Production: DOCUMENTS_PATH env, e.g. /mnt/user/appdata/estate-organiser/documents
  // In Docker, this will be mounted as /data/documents mapping to host /mnt/user/appdata/estate-organiser/documents
  // Demo mode uses isolated folder so fictional files do not mix with real ones
  if (process.env.NODE_ENV === "development" && process.env.DEV_AUTH_ENABLED === "true") {
    return process.env.DEMO_DOCUMENTS_PATH || "./data/demo-documents";
  }
  return process.env.DOCUMENTS_PATH || "./data/documents";
}

export function ensureDocumentsPath() {
  const path = documentsPath();
  mkdirSync(path, { recursive: true });
  return path;
}

export function safeStorageName(originalName: string) {
  // Generate safe storage name: uuid + safe extension
  const ext = extname(originalName).toLowerCase().slice(0, 20);
  // Only allow alphanumeric extension, 2-10 chars, otherwise no extension
  const safeExt = /^[a-z0-9]{1,10}$/.test(ext.replace(".", "")) ? ext : "";
  // Prevent path traversal – basename only, uuid for uniqueness
  return `${randomUUID()}${safeExt}`;
}

export function safeOriginalName(name: string) {
  // Strip path, limit length, remove control chars
  const base = basename(name).replace(/[\x00-\x1f\x7f]/g, "").trim();
  return base.slice(0, 200) || "document";
}

export function fullPath(storageName: string) {
  // Prevent path traversal – storageName is generated by us, but still validate
  if (storageName.includes("/") || storageName.includes("\\") || storageName.includes("..")) {
    throw new Error("Invalid storage name");
  }
  return join(documentsPath(), storageName);
}

export function exists(storageName: string) {
  return existsSync(fullPath(storageName));
}
